-- IssueVault Oracle schema
-- Run as application schema user (e.g., ISSUEVAULT_APP)

CREATE TABLE roles (
    role_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    role_name VARCHAR2(50 CHAR) NOT NULL,
    description VARCHAR2(255 CHAR),
    CONSTRAINT uq_roles_role_name UNIQUE (role_name)
);

CREATE TABLE teams (
    team_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    team_name VARCHAR2(120 CHAR) NOT NULL,
    description VARCHAR2(255 CHAR),
    CONSTRAINT uq_teams_team_name UNIQUE (team_name)
);

CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(80 CHAR) NOT NULL,
    full_name VARCHAR2(150 CHAR) NOT NULL,
    email VARCHAR2(150 CHAR) NOT NULL,
    password_hash VARCHAR2(500 CHAR) NOT NULL,
    role_id NUMBER NOT NULL,
    team_id NUMBER,
    is_active CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    last_login_at TIMESTAMP,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT ck_users_is_active CHECK (is_active IN ('Y', 'N')),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (role_id),
    CONSTRAINT fk_users_team FOREIGN KEY (team_id) REFERENCES teams (team_id)
);

CREATE TABLE issue_categories (
    category_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(120 CHAR) NOT NULL,
    description VARCHAR2(400 CHAR),
    is_active CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CONSTRAINT uq_issue_categories_name UNIQUE (category_name),
    CONSTRAINT ck_issue_categories_active CHECK (is_active IN ('Y', 'N'))
);

CREATE TABLE issue_tags (
    tag_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    tag_name VARCHAR2(80 CHAR) NOT NULL,
    CONSTRAINT uq_issue_tags_name UNIQUE (tag_name)
);

CREATE TABLE releases (
    release_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    release_name VARCHAR2(80 CHAR) NOT NULL,
    release_date DATE,
    notes VARCHAR2(1000 CHAR),
    CONSTRAINT uq_releases_release_name UNIQUE (release_name)
);

CREATE TABLE issues (
    issue_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title VARCHAR2(250 CHAR) NOT NULL,
    description CLOB NOT NULL,
    module_name VARCHAR2(120 CHAR) NOT NULL,
    environment VARCHAR2(120 CHAR),
    severity VARCHAR2(20 CHAR) NOT NULL,
    priority VARCHAR2(20 CHAR) NOT NULL,
    status VARCHAR2(30 CHAR) DEFAULT 'New' NOT NULL,
    category_id NUMBER NOT NULL,
    error_code VARCHAR2(80 CHAR),
    steps_to_reproduce CLOB,
    expected_result CLOB,
    actual_result CLOB,
    business_impact CLOB,
    reported_by NUMBER NOT NULL,
    assigned_to NUMBER,
    release_id NUMBER,
    duplicate_of_issue_id NUMBER,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_issues_severity CHECK (severity IN ('Low', 'Medium', 'High', 'Critical')),
    CONSTRAINT ck_issues_priority CHECK (priority IN ('P1', 'P2', 'P3', 'P4')),
    CONSTRAINT ck_issues_status CHECK (
        status IN (
            'New',
            'Under Review',
            'Known Issue',
            'In Progress',
            'Waiting for User',
            'Resolved',
            'Closed',
            'Reopened'
        )
    ),
    CONSTRAINT fk_issues_category FOREIGN KEY (category_id) REFERENCES issue_categories (category_id),
    CONSTRAINT fk_issues_reported_by FOREIGN KEY (reported_by) REFERENCES users (user_id),
    CONSTRAINT fk_issues_assigned_to FOREIGN KEY (assigned_to) REFERENCES users (user_id),
    CONSTRAINT fk_issues_release FOREIGN KEY (release_id) REFERENCES releases (release_id),
    CONSTRAINT fk_issues_duplicate_of FOREIGN KEY (duplicate_of_issue_id) REFERENCES issues (issue_id)
);

CREATE TABLE issue_status_history (
    history_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    issue_id NUMBER NOT NULL,
    old_status VARCHAR2(30 CHAR),
    new_status VARCHAR2(30 CHAR) NOT NULL,
    changed_by NUMBER NOT NULL,
    changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    notes VARCHAR2(1000 CHAR),
    CONSTRAINT fk_issue_history_issue FOREIGN KEY (issue_id) REFERENCES issues (issue_id) ON DELETE CASCADE,
    CONSTRAINT fk_issue_history_changed_by FOREIGN KEY (changed_by) REFERENCES users (user_id),
    CONSTRAINT ck_issue_history_status CHECK (
        new_status IN (
            'New',
            'Under Review',
            'Known Issue',
            'In Progress',
            'Waiting for User',
            'Resolved',
            'Closed',
            'Reopened'
        )
    )
);

CREATE TABLE issue_tag_map (
    issue_id NUMBER NOT NULL,
    tag_id NUMBER NOT NULL,
    created_by NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_issue_tag_map PRIMARY KEY (issue_id, tag_id),
    CONSTRAINT fk_issue_tag_map_issue FOREIGN KEY (issue_id) REFERENCES issues (issue_id) ON DELETE CASCADE,
    CONSTRAINT fk_issue_tag_map_tag FOREIGN KEY (tag_id) REFERENCES issue_tags (tag_id) ON DELETE CASCADE,
    CONSTRAINT fk_issue_tag_map_created_by FOREIGN KEY (created_by) REFERENCES users (user_id)
);

CREATE TABLE attachments (
    attachment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    issue_id NUMBER NOT NULL,
    original_filename VARCHAR2(255 CHAR) NOT NULL,
    stored_filename VARCHAR2(255 CHAR) NOT NULL,
    file_path VARCHAR2(500 CHAR) NOT NULL,
    file_size_bytes NUMBER NOT NULL,
    content_type VARCHAR2(120 CHAR),
    uploaded_by NUMBER NOT NULL,
    uploaded_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_attachments_issue FOREIGN KEY (issue_id) REFERENCES issues (issue_id) ON DELETE CASCADE,
    CONSTRAINT fk_attachments_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (user_id)
);

CREATE TABLE comments (
    comment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    issue_id NUMBER NOT NULL,
    commented_by NUMBER NOT NULL,
    comment_text CLOB NOT NULL,
    is_internal CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_comments_internal CHECK (is_internal IN ('Y', 'N')),
    CONSTRAINT fk_comments_issue FOREIGN KEY (issue_id) REFERENCES issues (issue_id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_commented_by FOREIGN KEY (commented_by) REFERENCES users (user_id)
);

CREATE TABLE resolutions (
    resolution_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    issue_id NUMBER NOT NULL,
    root_cause CLOB NOT NULL,
    workaround CLOB,
    final_fix CLOB NOT NULL,
    resolution_steps CLOB NOT NULL,
    resolver_id NUMBER NOT NULL,
    resolved_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    resolution_minutes NUMBER,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_resolutions_issue UNIQUE (issue_id),
    CONSTRAINT fk_resolutions_issue FOREIGN KEY (issue_id) REFERENCES issues (issue_id) ON DELETE CASCADE,
    CONSTRAINT fk_resolutions_resolver FOREIGN KEY (resolver_id) REFERENCES users (user_id)
);

CREATE TABLE linked_issues (
    link_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    issue_id NUMBER NOT NULL,
    linked_issue_id NUMBER NOT NULL,
    link_type VARCHAR2(30 CHAR) NOT NULL,
    created_by NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_linked_issues_type CHECK (
        link_type IN ('duplicate', 'parent', 'dependent', 'recurring', 'blocker')
    ),
    CONSTRAINT ck_linked_issues_not_self CHECK (issue_id <> linked_issue_id),
    CONSTRAINT uq_linked_issue UNIQUE (issue_id, linked_issue_id, link_type),
    CONSTRAINT fk_linked_issues_issue FOREIGN KEY (issue_id) REFERENCES issues (issue_id) ON DELETE CASCADE,
    CONSTRAINT fk_linked_issues_linked FOREIGN KEY (linked_issue_id) REFERENCES issues (issue_id) ON DELETE CASCADE,
    CONSTRAINT fk_linked_issues_created_by FOREIGN KEY (created_by) REFERENCES users (user_id)
);

CREATE TABLE solution_feedback (
    feedback_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    issue_id NUMBER NOT NULL,
    resolution_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    rating NUMBER(2, 1) NOT NULL,
    is_helpful CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    comments VARCHAR2(1000 CHAR),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_solution_feedback_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ck_solution_feedback_helpful CHECK (is_helpful IN ('Y', 'N')),
    CONSTRAINT fk_solution_feedback_issue FOREIGN KEY (issue_id) REFERENCES issues (issue_id) ON DELETE CASCADE,
    CONSTRAINT fk_solution_feedback_resolution FOREIGN KEY (resolution_id) REFERENCES resolutions (resolution_id) ON DELETE CASCADE,
    CONSTRAINT fk_solution_feedback_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE knowledge_articles (
    article_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    issue_id NUMBER,
    title VARCHAR2(250 CHAR) NOT NULL,
    summary CLOB,
    article_body CLOB NOT NULL,
    created_by NUMBER NOT NULL,
    published_at TIMESTAMP,
    is_published CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    helpful_votes NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT ck_knowledge_article_published CHECK (is_published IN ('Y', 'N')),
    CONSTRAINT fk_knowledge_issue FOREIGN KEY (issue_id) REFERENCES issues (issue_id),
    CONSTRAINT fk_knowledge_created_by FOREIGN KEY (created_by) REFERENCES users (user_id)
);

CREATE INDEX idx_issues_title_upper ON issues (UPPER(title));
CREATE INDEX idx_issues_error_code ON issues (error_code);
CREATE INDEX idx_issues_module_name ON issues (module_name);
CREATE INDEX idx_issues_severity ON issues (severity);
CREATE INDEX idx_issues_status ON issues (status);
CREATE INDEX idx_issues_created_at ON issues (created_at);
CREATE INDEX idx_issues_assigned_to ON issues (assigned_to);

CREATE INDEX idx_comments_issue ON comments (issue_id, created_at);
CREATE INDEX idx_status_history_issue ON issue_status_history (issue_id, changed_at);
CREATE INDEX idx_solution_feedback_issue ON solution_feedback (issue_id);
CREATE INDEX idx_attachments_issue ON attachments (issue_id);

CREATE OR REPLACE TRIGGER trg_issues_updated_at
BEFORE UPDATE ON issues
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_resolutions_updated_at
BEFORE UPDATE ON resolutions
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/
